replicaCount: 1
image:
  repository: my-registry:5000/my-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: default

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: my-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /healthcheck
    port: 9000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthcheck
    port: 9000
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

envSecrets:
  - name: BACKEND_ORIGINS
    secretName: argocd-credentials
    secretKey: BACKEND_ORIGINS
  - name: FASTAPI_PROJECT_NAME
    secretName: argocd-credentials
    secretKey: FASTAPI_PROJECT_NAME
  - name: LOG_LEVEL
    secretName: argocd-credentials
    secretKey: LOG_LEVEL
  - name: ENVIRONMENT
    secretName: argocd-credentials
    secretKey: ENVIRONMENT
  - name: ARGOCD_SERVER
    secretName: argocd-credentials
    secretKey: ARGOCD_SERVER
  - name: ARGOCD_PORT
    secretName: argocd-credentials
    secretKey: ARGOCD_PORT
  - name: ARGOCD_URL
    secretName: argocd-credentials
    secretKey: ARGOCD_URL
  - name: ARGOCD_PASSWORD
    secretName: argocd-credentials
    secretKey: ARGOCD_PASSWORD
  - name: ARGOCD_USERNAME
    secretName: argocd-credentials
    secretKey: ARGOCD_USERNAME
  - name: TOKEN_CACHE_TTL
    secretName: argocd-credentials
    secretKey: TOKEN_CACHE_TTL
  - name: IGNORE_SERVER_ERROR
    secretName: argocd-credentials
    secretKey: IGNORE_SERVER_ERROR
  - name: ALLOW_INSECURE
    secretName: argocd-credentials
    secretKey: ALLOW_INSECURE
