replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: nginx.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}

autoscaling:
  enabled: false

serviceAccount:
  create: false